language: cpp

sudo: required

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - libpcap-dev
    - libssl-dev
    - libboost-all-dev
    
install:
  - chmod +x conan_scripts/install.sh
  - ./conan_scripts/install.sh

before_script:
  - mkdir build
  - cd build
  - cmake .. -DLIBTINS_ENABLE_CXX11=1
  - make tests

script:
  - ctest -V
  
after_script:
  - chmod +x conan_scripts/run.sh
  - ./conan_scripts/run.sh